# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Generates Plant UML diagrams from workspace
      - name: Export Structurizr workspace
        uses: addnab/docker-run-action@v3
        with:
          image: structurizr/cli:latest
          options: -v ${{ github.workspace }}:/var/www
          run: '/usr/local/structurizr-cli/structurizr.sh export -w /var/www/model/workspace.dsl -f plantuml/c4plantuml -o /var/www/target/puml'

      # Prepare SVG diagrams in website/static/diagrams
      - name: Render PlantUML diagrams
        uses: addnab/docker-run-action@v3
        with:
          image: plantuml/plantuml:latest
          options: -v ${{ github.workspace }}:/var/www
          run: java -jar /opt/plantuml.jar -svg -o /var/www/website/static/diagrams /var/www/model/.generated

      # Build docusaurus website
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm ci
        working-directory: ./website
        
      - name: Build website
        run: npm run build
        working-directory: ./website

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: website/build

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
